const connection = require("../config/connection");
const { User, Thought } = require("../models");

// Define seed data with more creative and unique thoughts
const thoughtData = [
  {
    thoughtText: "Imagine a world where cats can talk and discuss their daily adventures...",
    username: "catlover123",
  // userId will be automatically generated by MongoDB
  },
  {
    thoughtText: "What if we could fly without the need for airplanes or wings? How amazing would that be?",
    username: "flightdreamer",
    // userId will be automatically generated by MongoDB
  },
  {
    thoughtText: "In a parallel universe, we might be having this conversation in a completely different language...",
    username: "multiverseexplorer",
    // userId will be automatically generated by MongoDB
  },
  {
    thoughtText: "What if time travel was possible? I'd love to visit ancient civilizations and witness history firsthand.",
    username: "timetraveler2023",
    // userId will be automatically generated by MongoDB
  },
  {
    thoughtText: "If trees could communicate, they'd have some fascinating stories to share about the changing seasons.",
    username: "naturelover",
    // userId will be automatically generated by MongoDB
  },
];

// Define user data with unique usernames and emails
const userData = [
  {
    username: "user1",
    email: "user1@example.com",
  },
  {
    username: "user2",
    email: "user2@example.com",
  },
  {
    username: "user3",
    email: "user3@example.com",
  },
  {
    username: "user4",
    email: "user4@example.com",
  },
  {
    username: "user5",
    email: "user5@example.com",
  },
];

// Start the seeding runtime timer
console.time("seeding");

// Create connection to MongoDB
connection.once("open", async () => {
  try {
    // Drop collections if they exist
    await Promise.all([User.collection.drop(), Thought.collection.drop()]);

    // Insert user data into the User collection and get generated user IDs
    const userList = await User.insertMany(userData);

    // Insert thought data into the Thought collection
    const updatedThoughtData = thoughtData.map((thought, index) => ({
      ...thought,
      userId: userList[index]._id,
    }));

    const thoughtList = await Thought.insertMany(updatedThoughtData);

    // Assign each thought to a random user
    for (const thought of thoughtList) {
      const randomUser = userList[Math.floor(Math.random() * userList.length)];
      randomUser.thoughts.push(thought._id);
      await randomUser.save();
    }

    // Print the results
    console.log("User data inserted:", userList);
    console.log("Thought data inserted:", thoughtList);
    console.timeEnd("Seeding Complete");
  } catch (err) {
    console.error("Seeding error:", err);
  } finally {
    process.exit(0);
  }
});
